#!/usr/bin/env python3
"""regen_incident_index.py — rebuild docs/incidents/INDEX.md from front-matter.

Walks docs/incidents/*.md, parses YAML front-matter, writes a sortable
markdown table to INDEX.md. This is the file regulators / CCO would query
first when asking "show me all production issues in <range>".

Usage:
    regen_incident_index.py           # writes docs/incidents/INDEX.md
    regen_incident_index.py --dry-run # prints to stdout

Run after creating or updating any postmortem file (or via a cron — see
docs/OBSERVABILITY_STANDARD.md "Postmortem Policy").
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

INCIDENTS_DIR = Path("/home/nixos/Prod/V1/docs/incidents")


def parse_front_matter(path: Path) -> dict | None:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        return None
    end = text.find("\n---\n", 4)
    if end < 0:
        return None
    out: dict = {}
    for line in text[4:end].splitlines():
        line = line.split("#", 1)[0].rstrip()
        if not line or ":" not in line:
            continue
        k, _, v = line.partition(":")
        v = v.strip()
        if v.startswith("[") and v.endswith("]"):
            v = [t.strip() for t in v[1:-1].split(",") if t.strip()]
        out[k.strip()] = v
    return out


def build_index() -> str:
    records = []
    for path in sorted(INCIDENTS_DIR.glob("*.md")):
        if path.name in ("INDEX.md", "TEMPLATE.md"):
            continue
        m = parse_front_matter(path)
        if not m:
            # File without front-matter — show but flag
            records.append({
                "date": "?",
                "severity": "?",
                "category": "?",
                "component": "?",
                "status": "?",
                "summary": f"_(no front-matter)_ — {path.name}",
                "slug": path.stem,
                "_legacy": True,
            })
            continue
        m["slug"] = path.stem
        records.append(m)

    # Sort by date desc (newest first)
    records.sort(key=lambda r: (r.get("date") or ""), reverse=True)

    counts = {"P0":0,"P1":0,"P2":0,"P3":0,"?":0}
    cats: dict[str,int] = {}
    statuses: dict[str,int] = {}
    for r in records:
        counts[(r.get("severity") or "?").upper()] = counts.get((r.get("severity") or "?").upper(),0)+1
        cats[r.get("category") or "?"] = cats.get(r.get("category") or "?", 0) + 1
        statuses[r.get("status") or "?"] = statuses.get(r.get("status") or "?", 0) + 1

    lines = [
        "# Incident Index",
        "",
        "**Auto-generated by `scripts/regen_incident_index.py`.** Do not edit by hand —",
        "edit the per-incident files under `docs/incidents/<slug>.md` and re-run the",
        "regenerator (or wait for the daily cron). Front-matter schema is documented",
        "in `docs/incidents/TEMPLATE.md`.",
        "",
        "**Policy:** every production-tool failure, every user-visible outage, and",
        "every client-affecting issue gets a postmortem here. See ",
        "`docs/OBSERVABILITY_STANDARD.md` § Postmortem Policy.",
        "",
        f"**Total incidents on file:** {len(records)}",
        "",
        "## Counts",
        "",
        f"- **By severity:** P0={counts.get('P0',0)} · P1={counts.get('P1',0)} · "
        f"P2={counts.get('P2',0)} · P3={counts.get('P3',0)}"
        + (f" · ?={counts['?']}" if counts.get('?',0) else ""),
        f"- **By category:** " + ", ".join(f"`{c}`={n}" for c,n in sorted(cats.items())),
        f"- **By status:** " + ", ".join(f"{s}={n}" for s,n in sorted(statuses.items())),
        "",
        "## All incidents (newest first)",
        "",
        "| Date | Sev | Category | Component | Status | Summary | File |",
        "|---|---|---|---|---|---|---|",
    ]
    for r in records:
        slug = r["slug"]
        d = r.get("date","?")
        sev = (r.get("severity") or "?").upper()
        cat = r.get("category","?")
        comp = f"`{r.get('component','?')}`"
        status = r.get("status","?")
        summ = r.get("summary","?")
        # Markdown-escape any pipes in the summary
        summ = summ.replace("|","\\|")
        lines.append(f"| {d} | {sev} | {cat} | {comp} | {status} | {summ} | [`{slug}.md`](./{slug}.md) |")

    lines.append("")
    lines.append("## How to query (for CCO / regulators)")
    lines.append("")
    lines.append("```bash")
    lines.append("# All P0/P1 incidents in May 2026:")
    lines.append("grep -l 'date: 2026-05' docs/incidents/*.md \\")
    lines.append("  | xargs grep -lE '^severity:\\s*(P0|P1)'")
    lines.append("")
    lines.append("# All client-facing incidents ever:")
    lines.append("grep -l '^category: client' docs/incidents/*.md")
    lines.append("")
    lines.append("# All currently-open incidents:")
    lines.append("grep -l '^status: open' docs/incidents/*.md")
    lines.append("```")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()
    index = build_index()
    if args.dry_run:
        print(index)
        return 0
    out = INCIDENTS_DIR / "INDEX.md"
    out.write_text(index, encoding="utf-8")
    print(f"wrote {out} ({len(index)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
